# Generated by Django 5.1.1 on 2025-03-25 14:48
import uuid
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DynamicTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="Plugin",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("description", models.CharField(max_length=4096)),
                ("schema", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Server",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="DynamicColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=50)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.dynamictable",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dynamictable",
            name="plugin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.plugin"
            ),
        ),
        migrations.CreateModel(
            name="ServerPlugins",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(blank=True, max_length=16, null=True)),
                ("start_date", models.DateTimeField()),
                (
                    "expire_date",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2025,
                            3,
                            25,
                            14,
                            48,
                            55,
                            295698,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                (
                    "plugin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="api.plugin"
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="api.server"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="server",
            name="plugins",
            field=models.ManyToManyField(
                related_name="servers", through="api.ServerPlugins", to="api.plugin"
            ),
        ),
    ]
