# Generated by Django 5.1.1 on 2024-09-08 14:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DynamicTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="Plugin",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("description", models.CharField(max_length=4096)),
                ("schema", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DynamicColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=50)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.dynamictable",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dynamictable",
            name="plugin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.plugin"
            ),
        ),
    ]
