# Generated by Django 5.1.1 on 2025-03-25 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serverplugins",
            name="expire_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 4, 24, 15, 2, 30, 487953, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
