# Generated by Django 5.1.1 on 2025-03-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pluginversion",
            name="deprecated",
            field=models.BooleanField(default=False),
        ),
    ]
