# Generated by Django 5.1.1 on 2024-09-08 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_plugin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plugin',
            name='server',
        ),
        migrations.CreateModel(
            name='ServerPlugins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=16)),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.plugin')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.server')),
            ],
        ),
        migrations.AddField(
            model_name='server',
            name='plugins',
            field=models.ManyToManyField(related_name='servers', through='api.ServerPlugins', to='api.plugin'),
        ),
    ]
